---
- name: Open rabbitmq admin console port
  community.general.ufw:
    rule: allow
    port: '15672'
    proto: tcp

- name: Open rabbitmq port
  community.general.ufw:
    rule: allow
    port: '5672'
    from_ip: 127.0.0.1
    to_ip: 127.0.0.1
    proto: tcp
# tasks file for /etc/ansible/roles/rabbitmq
